# Generated by Django 5.2.4 on 2025-08-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_course',
            field=models.PositiveSmallIntegerField(help_text='Kurs davomiyligi'),
        ),
    ]
